### ISSUE TITLE
Updates stop after internet goes down

### ISSUE THREAD

**Issue by scottbruns** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#127]
Status updates stop when my internet goes down for a minute. 

The status updates will not start working working again until I restart Home Assistant.

I am running version e583bd0.

**Comment by TechHummel** [comment]
Can you provide logs and more information please (which device, ids, etc.?), thanks!

**Comment by scottbruns** [comment]
Initial Log after setting HomeWhiz Logs to Debug and restarting Home Assistant:

2023-04-25 15:18:50.088 INFO (MainThread) [homeassistant.setup] Setting up homewhiz
2023-04-25 15:18:50.088 INFO (MainThread) [homeassistant.setup] Setup of domain homewhiz took 0.0 seconds
2023-04-25 15:18:50.135 INFO (MainThread) [custom_components.homewhiz] Setting up entry F999969575108805449716
2023-04-25 15:18:50.135 INFO (MainThread) [custom_components.homewhiz] Setting up cloud connection
2023-04-25 15:18:50.314 INFO (MainThread) [homeassistant.components.select] Setting up select.homewhiz
2023-04-25 15:18:50.315 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.homewhiz
2023-04-25 15:18:50.327 DEBUG (MainThread) [custom_components.homewhiz] Selects: ['STATE', 'DISHWASHER_PROGRAM', 'SETTING_DETERGENT_TYPE', 'DISHWASHER_RINSE_AID_LEVEL']
2023-04-25 15:18:50.329 INFO (MainThread) [homeassistant.components.climate] Setting up climate.homewhiz
2023-04-25 15:18:50.336 DEBUG (MainThread) [custom_components.homewhiz] Sensors: ['STATE', 'DISHWASHER_PROGRAM', 'SUB_STATE', 'DISHWASHER_DELAY', 'DISHWASHER_DURATION', 'DISHWASHER_REMAINING', 'SETTING_DETERGENT_TYPE', 'DISHWASHER_RINSE_AID_LEVEL']
2023-04-25 15:18:50.340 INFO (MainThread) [homeassistant.components.switch] Setting up switch.homewhiz
2023-04-25 15:18:50.350 DEBUG (MainThread) [custom_components.homewhiz] ACs: []
2023-04-25 15:18:50.355 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.homewhiz
2023-04-25 15:18:50.363 DEBUG (MainThread) [custom_components.homewhiz] Switches: ['DISHWASHER_DEEPWASH', 'DISHWASHER_FAST+', 'DISHWASHER_STEAMGLOSS', 'DISHWASHER_SANITIZE', 'DISHWASHER_HALFLOAD', 'SETTING_AUTO_DOOR', 'SETTING_ODOUR_REMOVAL', 'SETTING_MICRO_FILTER_CLEANING', 'SETTING_INNER_ILLUMINATION']
2023-04-25 15:18:50.375 DEBUG (MainThread) [custom_components.homewhiz] Binary sensors: ['REMOTE_CONTROL', 'DISHWASHER_WARNING_NO_RINSE_AID', 'DISHWASHER_WARNING_NO_WATER', 'DISHWASHER_WARNING_CHECK_THE_FILTER', 'DISHWASHER_WARNING_DOOR_IS_OPEN']
2023-04-25 15:18:50.432 INFO (MainThread) [custom_components.homewhiz] Connecting to F999969575108805449716
2023-04-25 15:18:51.659 DEBUG (MainThread) [custom_components.homewhiz] Credentials expire at: 2023-04-25 16:18:51
2023-04-25 15:18:53.390 DEBUG (MainThread) [custom_components.homewhiz] Subscribe to update result: {'packet_id': 1, 'topic': '$aws/things/F999969575108805449716/shadow/update/accepted', 'qos': <QoS.AT_LEAST_ONCE: 1>}
2023-04-25 15:18:53.605 DEBUG (MainThread) [custom_components.homewhiz] Subscribe to get result: {'packet_id': 2, 'topic': '$aws/things/F999969575108805449716/shadow/get/accepted', 'qos': <QoS.AT_LEAST_ONCE: 1>}
2023-04-25 15:18:53.608 DEBUG (MainThread) [custom_components.homewhiz] Force read result: {'packet_id': 3}
2023-04-25 15:18:53.610 DEBUG (MainThread) [custom_components.homewhiz] Get shadow result: {'packet_id': 4}
2023-04-25 15:18:53.611 DEBUG (MainThread) [custom_components.homewhiz] Set hass time interval update
2023-04-25 15:18:53.863 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x80\x80\x80\x00\x08\x00\x00\x01\x03\x11\x00\x00\x01\x01\x00\x00\x80\x00\x00\x01\xff\x14 \x00\x00\x01\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 15:18:53.863 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 15:18:54.068 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x80\x80\x80\x00\x08\x00\x00\x01\x03\x11\x00\x00\x01\x01\x00\x00\x80\x00\x00\x01\xff\x14 \x00\x00\x01\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 15:18:54.068 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 15:19:53.616 DEBUG (SyncWorker_0) [custom_components.homewhiz] Force read result: {'packet_id': 5}
2023-04-25 15:19:53.861 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x80\x80\x80\x00\x08\x00\x00\x01\x03\x11\x00\x00\x01\x01\x00\x00\x80\x00\x00\x01\xff\x14 \x00\x00\x01\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 15:19:53.861 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data

I'll try to make it fail and then upload the new log.

**Comment by scottbruns** [comment]
I unplugged my network from my cable modem. I see the connection issues in the logs. But, when I reconnected the network, HomeWhiz reconnected and updated the status again.

2023-04-25 15:32:53.631 DEBUG (SyncWorker_13) [custom_components.homewhiz] Force read result: {'packet_id': 18}
2023-04-25 15:32:53.868 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x80\x80\x80\x00\x08\x00\x00\x01\x03\x11\x00\x00\x01\x01\x00\x00\x80\x00\x00\x01\xff\x14 \x00\x00\x01\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 15:32:53.868 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 15:33:53.634 DEBUG (SyncWorker_4) [custom_components.homewhiz] Force read result: {'packet_id': 19}
2023-04-25 15:33:53.911 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x80\x80\x80\x00\x08\x00\x00\x01\x03\x11\x00\x00\x01\x01\x00\x00\x80\x00\x00\x01\xff\x14 \x00\x00\x01\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 15:33:53.911 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 15:34:53.642 DEBUG (SyncWorker_3) [custom_components.homewhiz] Force read result: {'packet_id': 20}
2023-04-25 15:34:53.906 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x80\x80\x80\x00\x08\x00\x00\x01\x03\x11\x00\x00\x01\x01\x00\x00\x80\x00\x00\x01\xff\x14\x00\x00\x00\x01\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 15:34:53.906 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 15:35:53.640 DEBUG (SyncWorker_12) [custom_components.homewhiz] Force read result: {'packet_id': 21}
2023-04-25 15:35:53.871 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x80\x80\x80\x00\x08\x00\x00\x01\x03\x11\x00\x00\x01\x01\x00\x00\x80\x00\x00\x01\xff\x14 \x00\x00\x01\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 15:35:53.871 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 15:36:53.642 DEBUG (SyncWorker_10) [custom_components.homewhiz] Force read result: {'packet_id': 22}
2023-04-25 15:37:53.643 DEBUG (SyncWorker_6) [custom_components.homewhiz] Force read result: {'packet_id': 23}
2023-04-25 15:38:53.644 DEBUG (SyncWorker_1) [custom_components.homewhiz] Force read result: {'packet_id': 25}
2023-04-25 15:38:56.263 DEBUG (Dummy-18) [custom_components.homewhiz] Connection interrupted AWS_ERROR_MQTT_TIMEOUT: Time limit between request and response has been exceeded.
File "/config/custom_components/homewhiz/cloud.py", line 175, in force_read
File "/config/custom_components/homewhiz/cloud.py", line 175, in force_read
File "/config/custom_components/homewhiz/cloud.py", line 175, in force_read
2023-04-25 15:42:37.736 DEBUG (Dummy-18) [custom_components.homewhiz] Connection resumed

The connection errors I got were caused by external issue with my internet provider, so the connection issue might be different than what's happening when I disconnect my network cable. 

I'll try powering off my modem to see if that makes a difference.

**Comment by scottbruns** [comment]
I powered off the cable modem for 5 minutes. Powered it back up and HomeWhiz reconnected.

2023-04-25 15:53:53.691 DEBUG (SyncWorker_6) [custom_components.homewhiz] Force read result: {'packet_id': 37}
2023-04-25 15:53:53.924 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x07\x80\x80\x80\x80\x00\x08\x00\x00\x01\x00\x0f\x00\x00\x01\x01\x00\x00\x80\x00\x00\x01\x1c\n\x00\x00\x00\x01\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 15:53:53.924 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 15:54:53.694 DEBUG (SyncWorker_7) [custom_components.homewhiz] Force read result: {'packet_id': 38}
2023-04-25 15:54:53.921 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x07\x80\x80\x80\x80\x00\x08\x00\x00\x01\x00\x0f\x00\x00\x01\x01\x00\x00\x80\x00\x00\x01\x1c\n\x00\x00\x00\x01\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 15:54:53.921 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 15:55:53.694 DEBUG (SyncWorker_0) [custom_components.homewhiz] Force read result: {'packet_id': 39}
2023-04-25 15:56:53.709 DEBUG (SyncWorker_2) [custom_components.homewhiz] Force read result: {'packet_id': 40}
2023-04-25 15:57:53.711 DEBUG (SyncWorker_1) [custom_components.homewhiz] Force read result: {'packet_id': 41}
2023-04-25 15:58:53.715 DEBUG (SyncWorker_6) [custom_components.homewhiz] Force read result: {'packet_id': 42}
2023-04-25 15:59:53.717 DEBUG (SyncWorker_3) [custom_components.homewhiz] Force read result: {'packet_id': 43}
2023-04-25 16:00:53.720 DEBUG (SyncWorker_9) [custom_components.homewhiz] Force read result: {'packet_id': 44}
2023-04-25 16:01:53.720 DEBUG (SyncWorker_3) [custom_components.homewhiz] Force read result: {'packet_id': 45}
2023-04-25 16:02:40.797 DEBUG (Dummy-18) [custom_components.homewhiz] Connection interrupted AWS_ERROR_MQTT_TIMEOUT: Time limit between request and response has been exceeded.
2023-04-25 16:02:46.911 DEBUG (Dummy-18) [custom_components.homewhiz] Connection resumed
2023-04-25 16:02:46.970 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x87\x80\x80\x80\x80\x80\x88\x00\x00\t\x00\x0f\x80\x80\x81\x81\x80\x80\x80\x80\x00\x01Q\x1e\x00 \x00\x81\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 16:02:46.970 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 16:02:46.974 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x87\x80\x80\x80\x80\x80\x88\x00\x00\t\x00\x0f\x80\x80\x81\x81\x80\x80\x80\x80\x00\x01Q\x1e\x00 \x00\x81\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 16:02:46.974 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 16:02:46.975 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x87\x80\x80\x80\x80\x80\x88\x00\x00\t\x00\x0f\x80\x80\x81\x81\x80\x80\x80\x80\x00\x01Q\x1e\x00 \x00\x81\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 16:02:46.975 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 16:02:46.976 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x87\x80\x80\x80\x80\x80\x88\x00\x00\t\x00\x0f\x80\x80\x81\x81\x80\x80\x80\x80\x00\x01Q\x1e\x00 \x00\x81\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 16:02:46.976 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 16:02:47.112 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x87\x80\x80\x80\x80\x80\x88\x00\x00\t\x00\x0f\x80\x80\x81\x81\x80\x80\x80\x80\x00\x01Q\x1e\x00 \x00\x81\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 16:02:47.112 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 16:02:47.113 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x87\x80\x80\x80\x80\x80\x88\x00\x00\t\x00\x0f\x80\x80\x81\x81\x80\x80\x80\x80\x00\x01Q\x1e\x00 \x00\x81\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 16:02:47.113 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 16:02:47.132 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x87\x80\x80\x80\x80\x80\x88\x00\x00\t\x00\x0f\x80\x80\x81\x81\x80\x80\x80\x80\x00\x01Q\x1e\x00 \x00\x81\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 16:02:47.133 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-25 16:02:53.727 DEBUG (SyncWorker_9) [custom_components.homewhiz] Force read result: {'packet_id': 47}
2023-04-25 16:02:53.933 DEBUG (Dummy-18) [custom_components.homewhiz] Message received: bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x00\x00\xff\x00\x00\x87\x80\x80\x80\x80\x80\x88\x00\x00\t\x00\x0f\x80\x80\x81\x81\x80\x80\x80\x80\x00\x01Q\x1e\x00 \x00\x81\x13\xf8\xff\x00\x00\x00\x00\x00')
2023-04-25 16:02:53.933 DEBUG (Dummy-18) [custom_components.homewhiz] Manually updated homewhiz data

I guess I'll have to look at the logs if/when the issue happens again.

**Comment by elektrolitr** [comment]
I think it may be related to the issue https://github.com/rowysock/home-assistant-HomeWhiz/issues/115

Couple days ago I had similar problem with router hanging up exactly at the time when Homewhiz needed to refresh credentials. The symptoms were similar: after web connection is restored, there's no update anymore until the integration (or HA) is restarted

I must admit I'm not running patch https://github.com/rowysock/home-assistant-HomeWhiz/pull/121 exactly to be able to trace down this issue. 
I'll try to recreate problem by disabling the network connection at the time when AWS credentials are updated

Some of the logs are below:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 174, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-24 07:34:36.965 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 101] Connect call failed ('13.33.243.120', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/homewhiz/cloud.py", line 158, in refresh_connection
    await self.connect()
  File "/config/custom_components/homewhiz/cloud.py", line 82, in connect
    credentials = await login(
  File "/config/custom_components/homewhiz/api.py", line 112, in login
    async with session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.arcelikiot.com:443 ssl:default [Connect call failed ('13.33.243.120', 443)]
2023-04-24 07:35:28.637 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 174, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-24 07:36:28.639 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 174, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.`

**Comment by elektrolitr** [comment]
@scottbruns 
Can you please check also the file "home-assistant.log.1" located in the /config folder? 
It's a backup of previous log (before restart). 
If you didn't restart HA more than once the file may contain information related to your problem

**Comment by scottbruns** [comment]
I restarted Home Assistant a few times so my home-assistant.log.1 file is too new. 

At least I know where to look if it happens again.

**Comment by TechHummel** [comment]
Nevertheless,  I can try to catch this exception and force a reconnect to make the connection more resilliant 😃
