### ISSUE TITLE
Failed to unload

### ISSUE THREAD

**Issue by Mikescotland** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#143]
Recently getting a lot of "Failed to unload" whenever i try to reload the component.
Here's debug

```
2023-07-19 15:46:38.471 DEBUG (MainThread) [custom_components.homewhiz] [XXX] Killing connection
2023-07-19 15:46:38.471 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Washer-Dryer for homewhiz
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/__init__.py", line 91, in async_unload_entry
    await hass.data[DOMAIN][entry.entry_id].kill()
  File "/config/custom_components/homewhiz/bluetooth.py", line 121, in kill
    await self._connection.disconnect()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 364, in disconnect
    return await self._backend.disconnect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 99, in _async_wrap_bluetooth_operation
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 368, in disconnect
    self._async_disconnected_cleanup()
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 198, in _async_disconnected_cleanup
    self._unsubscribe_connection_state()
  File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 174, in _unsubscribe_connection_state
    self._cancel_connection_state()
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/client.py", line 614, in unsub
    self._connection.remove_message_callback(on_msg, msg_types)
  File "/usr/local/lib/python3.11/site-packages/aioesphomeapi/connection.py", line 563, in remove_message_callback
    self._message_handlers[msg_type].remove(on_message)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: <class 'api_pb2.BluetoothDeviceConnectionResponse'>
```

**Comment by TechHummel** [comment]
Thanks for reporting this issue! 👍 
Could you please test if this issue still occurs with the latest beta release? Thanks!
