### ISSUE TITLE
Entry failed to set up

### ISSUE THREAD

**Issue by elektrolitr** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#169]
In my case the Dishwasher fails to set up, but due to the nature of the error, I suspect that any cloud- connected device will fail, too

![image](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/121390684/e341e482-07a8-4199-9a23-103fb3a0d519)

Error log: 

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/__init__.py", line 34, in async_setup_entry
    return await setup_cloud(entry, hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/__init__.py", line 77, in setup_cloud
    _lazy_install_awsiotsdk()
  File "/config/custom_components/homewhiz/__init__.py", line 71, in _lazy_install_awsiotsdk
    if not is_installed(pkg) and not install_package(pkg, find_links=links):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: install_package() got an unexpected keyword argument 'find_links'
2023-11-01 22:03:26.439 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Dishwasher for homewhiz
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/__init__.py", line 34, in async_setup_entry
    return await setup_cloud(entry, hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/__init__.py", line 77, in setup_cloud
    _lazy_install_awsiotsdk()
  File "/config/custom_components/homewhiz/__init__.py", line 71, in _lazy_install_awsiotsdk
    if not is_installed(pkg) and not install_package(pkg, find_links=links):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: install_package() got an unexpected keyword argument 'find_links'
`

The keyword argument "find_links" is removed from homeassistant.util.package in the update https://github.com/home-assistant/core/commit/664e490cfaf76d29185dcd85b22c72c4f1e21dbc

As a temporary fix, I removed the  "find_links=links" from the arguments in:
  File "/config/custom_components/homewhiz/__init__.py", line 71, in _lazy_install_awsiotsdk
    if not is_installed(pkg) and not install_package(pkg, find_links=links):
and got the dishwasher working, but I'm not sure if that has any unwanted effects

**Comment by Scialla** [comment]
Same problem here, with fridge, with HA core 2023.11.0 (with 2023.10.x work)

**Comment by TechHummel** [comment]
Thanks @elektrolitr, great that you were able to identify and fix the issue 👍 
If you want, you can raise a PR - else, I will do this later this weekend 😄

**Comment by patrickbeau** [comment]
Thanks Elektrolitr for the way :)
If you go through file changes, in util/package.py , you'll find the no more find_links existing.
Maybe you have to correct the init script for installing the module awsiotsdk ? 

(file changes link: https://github.com/home-assistant/core/compare/2023.10.5...2023.11.0 )
