### ISSUE TITLE
Failed to Setup Dishwasher 

### ISSUE THREAD

**Issue by earlparkly** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#176]
Hello, I have just installed a new Grundig Dishwasher that uses the Homewhiz app. Using the cloud connection option, it successfully lists the dishwasher but I get a Failed to Setup Device issue on the integration page that persists even after a Home Assistant restart. System error log is below if this helps? Please let me know if you need any more information.

Edit: Integration was added via HACS

```
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 12:31:11 (1 occurrences)
Last logged: 12:31:11

Error setting up entry Dishwasher for homewhiz
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/__init__.py", line 34, in async_setup_entry
    return await setup_cloud(entry, hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/__init__.py", line 77, in setup_cloud
    _lazy_install_awsiotsdk()
  File "/config/custom_components/homewhiz/__init__.py", line 71, in _lazy_install_awsiotsdk
    if not is_installed(pkg) and not install_package(pkg, find_links=links):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: install_package() got an unexpected keyword argument 'find_links'
```

**Comment by TechHummel** [comment]
Please look at this issue: https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/issues/174

**Comment by earlparkly** [comment]
Thank you and apologies
