### ISSUE TITLE
Entities always unavailable - Beko washing machine

### ISSUE THREAD

**Issue by FlorentGuedeau** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#183]
Hello, 
Happy new year everyone ! 
All my entities of my washing machine are always unavailable in bluetooth mode or cloud mode.
My washing machine is connected to the HomeWhiz app but datas never goes to HA.
Thx

**Comment by cannabarman** [comment]
Hi,
same problem here with a raspberry pi 4, device is found in Bluetooth mode but no data in HA (app is working fine). It's a Beko washing machine too.

**Comment by cannabarman** [comment]
Raspberry pi is 2,maybe 3 meters from the washing-machine. I have no Proxies, but it worked previously. I'll try to give logs soon.

**Comment by FlorentGuedeau** [comment]
Hello,

Here is the log :

> Logger: homeassistant
Source: custom_components/homewhiz/bluetooth.py:36
Integration: HomeWhiz ([documentation](https://github.com/rowysock/home-assistant-HomeWhiz), [issues](https://github.com/rowysock/home-assistant-HomeWhiz/issues))
First occurred: 08:51:13 (1 occurrences)
Last logged: 08:51:13
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 209, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbus_fast/aio/message_bus.py", line 375, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 363, in establish_connection
    await client.connect(
  File "/usr/local/lib/python3.11/site-packages/habluetooth/wrappers.py", line 295, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 146, in connect
    async with async_timeout(timeout):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/homewhiz/bluetooth.py", line 36, in connect
    self._connection = await establish_connection(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 387, in establish_connection
    _raise_if_needed(name, device.address, exc)
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 327, in _raise_if_needed
    raise BleakNotFoundError(msg) from exc
bleak_retry_connector.BleakNotFoundError: 00:A0:50:08:85:0C - 00:A0:50:08:85:0C: Failed to connect after 4 attempt(s): TimeoutError

**Comment by TechHummel** [comment]
The logs show that the integration is unsuccessfully trying to connect to the washing machine, therefore I do not believe that this is a bug in the integration.
Can you try to disable Bluetooth on your phone when using the washing machine? Maybe the Beko only supports one connected device and since you are using the app, it must be connected to your phone.

**Comment by FlorentGuedeau** [comment]
I've disabled bluetooth on my phone and integrations using bluetooth but i've the same error :

> Cette erreur provient d'une intégration personnalisée

Logger: homeassistant
Source: custom_components/homewhiz/bluetooth.py:36
Integration: HomeWhiz (documentation, issues)
First occurred: 11:19:58 (1 occurrences)
Last logged: 11:19:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 209, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbus_fast/aio/message_bus.py", line 375, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 363, in establish_connection
    await client.connect(
  File "/usr/local/lib/python3.11/site-packages/habluetooth/wrappers.py", line 295, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 146, in connect
    async with async_timeout(timeout):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/homewhiz/bluetooth.py", line 36, in connect
    self._connection = await establish_connection(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 387, in establish_connection
    _raise_if_needed(name, device.address, exc)
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 327, in _raise_if_needed
    raise BleakNotFoundError(msg) from exc
bleak_retry_connector.BleakNotFoundError: 00:A0:50:08:85:0C - 00:A0:50:08:85:0C: Failed to connect after 4 attempt(s): TimeoutError

**Comment by silardsimon** [comment]
Same issue here. I can configure the integration but the entities are always unavailable. Everything works fine in the app though.

**Comment by BCevin** [comment]
Same issue. connected trough cloud connection since my HA is located to far away (I think).

**Comment by ArthFink** [comment]
I have the same issue, but in my opinion, the problem lies at the washing machine. After 5-8 Days running without a hard rested (i.e. Disconnecting power), the Bluetooth module looks up. 
A different blocking dynamic is also that only one Bluetooth connection at a time can be established by the Beko Bluetooth module. So if the app on your phone is faster, then home assistant, the connection of home assistant fails. In this case, the only solution that I found is either to reboot or dis- and re-enable the integration.

**Comment by ReX1983** [comment]
Is there any chance to get this fixed? Unfortunately this issue makes the integration useless if you have a Bluetooth device.

**Comment by TechHummel** [comment]
Since the original reported issues are related to Bluetooth connection issues, I'll close this. 
The only recommendation I can give when it comes to Bluetooth problems is to try using a Bluetooth proxy (ESPHome).
