### ISSUE TITLE
Homewhiz not working following update

### ISSUE THREAD

**Issue by sinisterpuppy** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#210]
Hi team,

I've updated to the latest version today (v0.5.4) and it's failing to run.

I'm using a Pi 4b with HA in a docker.  (2024.4.2)

I initially lost connection to my device (failed to load), tried to remove and re-install and getting a 500 error

> Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

Logs say:

Logger: homeassistant
Source: requirements.py:318
First occurred: 22:11:04 (1 occurrences)
Last logged: 22:11:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 107, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 207, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 205, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1155, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1175, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1312, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2608, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2585, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 551, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 53, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 176, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 193, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 280, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 318, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for homewhiz not found: ['awsiotsdk'].

**Comment by TechHummel** [comment]
Thanks for your report! So, this was working before the update?

**Comment by sinisterpuppy** [comment]
Hey, yep was working perfectly fine including on the day of the update 

Following the update and the required restart the integration wouldn't load

**Comment by TechHummel** [comment]
Then I will undo https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/pull/192/commits/26bdab379a324e5a90f68b12e9e8183d3050ec04 - this should fix it! Thanks for reporting.

**Comment by mauriziov** [comment]
Hello, I was succesfully using the latest version (0.5.4)  until the last home assistant core update (2024.5.0), after update the HVAC entity is just disappeared. I' m using the HA core docker version in a PI4.

The log: 
Registratore: homeassistant.components.climate
Fonte: components/climate/__init__.py:363
Integrazione: Climatizzatore (documentazione, problemi)
Prima occorrenza: 06:54:57 (1 occorrenze)
Ultima registrazione: 06:54:57

Entity None (<class 'custom_components.homewhiz.climate.HomeWhizClimateEntity'>) implements HVACMode(s): cool, auto, dry, heat, fan_only, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/issues
