### ISSUE TITLE
With 0.5.6 data are read (available) again but after HA 2024.6.3 can't issue commands (write to appliance)

### ISSUE THREAD

**Issue by elmystico** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#226]
Something happened with 2024.6.3 update. I've reverted back to 0.5.4 and Homewhiz is dead as well with this version (before data were not refreshed but I could issue a HA service to refresh it and also commands/writes were working fine).
I have a Beko fridge, that I was able to control all of the settings thru HA before this happened

**Comment by elmystico** [comment]
Below only log I've got. Write errors are silent with default logging 


Rejestrator: homeassistant.helpers.entity
Źródło: helpers/entity.py:941
Pierwsze zdarzenie: 08:48:02 (2 zdarzenia)
Ostatnio zalogowany: 09:44:32

Update for switch.lodowka_none fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1289, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 529, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 262, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 288, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _async_update_data
    raise NotImplementedError("Update method not implemented")
NotImplementedError: Update method not implemented

**Comment by elmystico** [comment]
Sorry it seems working suddenly (no other system changes) for no apparent reason
