### ISSUE TITLE
All entities are N/A

### ISSUE THREAD

**Issue by kyselyna** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#240]
Hello,

The integration shows me all entities unknown, I have tried all versions but none of them work. It was not a problem before, but after several HA updates the integration unfortunately does not work. I am sending screenshots and logs below. Thank you

This is a BEKO 7165145600 washer and dryer, everything works normally in the app.

Core  -  2024.9.2
Supervisor  -  2024.09.1
Operating System  -  13.1
Frontend  -  20240909.1

![image](https://github.com/user-attachments/assets/47653a2e-81d6-40ec-8a88-caf2f7952398)

![image](https://github.com/user-attachments/assets/49b97de2-8ed9-46eb-af1a-de8cf4cc8df6)

LOG:
```
Logger: homeassistant
Zdroj: custom_components/homewhiz/bluetooth.py:43
integrace: HomeWhiz ([dokumentace](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz), [problémy](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/issues))
První výskyt: 18:20:42 (1 výskyty)
Naposledy logováno: 18:20:42

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/client.py", line 214, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dbus_fast/aio/message_bus.py", line 385, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bleak_retry_connector/__init__.py", line 363, in establish_connection
    await client.connect(
  File "/usr/local/lib/python3.12/site-packages/habluetooth/wrappers.py", line 311, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak/__init__.py", line 615, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/client.py", line 151, in connect
    async with async_timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/homewhiz/bluetooth.py", line 43, in connect
    self._connection = await establish_connection(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak_retry_connector/__init__.py", line 387, in establish_connection
    _raise_if_needed(name, device.address, exc)
  File "/usr/local/lib/python3.12/site-packages/bleak_retry_connector/__init__.py", line 327, in _raise_if_needed
    raise BleakNotFoundError(msg) from exc
bleak_retry_connector.BleakNotFoundError: 00:A0:50:B1:44:E5 - 00:A0:50:B1:44:E5: Failed to connect after 4 attempt(s): TimeoutError
```

[homewhiz full log.txt](https://github.com/user-attachments/files/17078052/homewhiz.full.log.txt)

**Comment by djrawe** [comment]
I have same issue, but without HA updates (2024.9.0)

**Comment by Mitchel85** [comment]
same here

**Comment by AznKid45** [comment]
And I have same issue

**Comment by Android1338** [comment]
Same here with Home Assistant version 2024.10.3 if used with the HomeWhiz cloud.

**Comment by thirsty1975** [comment]
gleiches Problem

**Comment by TechHummel** [comment]
Hi all 👋 
I'm afraid this is a Bluetooth connection issue which is outside the integration's control.
Please try using a Bluetooth proxy with ESPHome or maybe a different Bluetooth dongle.
