### ISSUE TITLE
Error during integration setup (cloud login)

### ISSUE THREAD

**Issue by VolchkovVlad** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#247]
```
2024-10-22 03:14:02.102 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\components\http\security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\components\http\forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\components\http\request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\components\http\ban.py", line 88, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\components\http\auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\components\http\headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\helpers\http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\components\http\decorators.py", line 71, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\components\config\config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\components\http\data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\helpers\data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\data_entry_flow.py", line 356, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\data_entry_flow.py", line 402, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\homeassistant\data_entry_flow.py", line 506, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\config\custom_components\homewhiz\config_flow.py", line 127, in async_step_bluetooth_connect
    id_response = await make_id_exchange_request(self._bt_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\config\custom_components\homewhiz\api.py", line 135, in make_id_exchange_request
    return from_dict(IdExchangeResponse, contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vladislavvolckov\Downloads\HassWP_2024.4.3\python-3.12.3.amd64\Lib\site-packages\dacite\core.py", line 69, in from_dict
    raise WrongTypeError(field_path=field.name, field_type=field_type, value=value)
dacite.exceptions.WrongTypeError: wrong value type for field "appId" - should be "str" instead of value "None" of type "NoneType"

```

<img width="1800" alt="Снимок экрана 2024-10-22 в 03 16 20" src="https://github.com/user-attachments/assets/4c4b7cf6-9452-40b4-9609-57e09b5d3f9e">

<img width="399" alt="Снимок экрана 2024-10-22 в 03 18 30" src="https://github.com/user-attachments/assets/d2ad4eee-7191-43b5-b85a-753bfb00bdb3">

**Comment by TechHummel** [comment]
Which version of home assistant are you using?
Could you please upload logs?

**Comment by VolchkovVlad** [comment]
> Which version of home assistant are you using? Could you please upload logs?

I'll answer later
