### ISSUE TITLE
Homewhiz loses connection 

### ISSUE THREAD

**Issue by djsjo** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#260]
Hallo,

it worked fine for a while but now it lost connection. This is the error log:

This error originated from a custom integration.

```
Logger: homeassistant
Source: custom_components/homewhiz/cloud.py:208
integration: HomeWhiz (documentation, issues)
First occurred: 06:28:15 (1 occurrences)
Last logged: 06:28:15

Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 208, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
                                        ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/site-packages/awscrt/mqtt.py", line 834, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
```

**Comment by TechHummel** [comment]
Is this happening regularly or only occasionally?

**Comment by djsjo** [comment]
It didnt occur again since then

**Comment by elmodem** [comment]
Had the exact same issue at the Same time. The problem disappeared on its own for me after 2 days. Probably connection problems to the HomeWhiz service.

**Comment by TechHummel** [comment]
Thanks for the feedback, then I'll close this issue for now. Just reopen if you are facing this issue again.
